language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "12"

script:
  - npm test

stages:
  - test
  - name: coverage
    if: branch = master

jobs:
  include:
    - stage: coverage
      node_js: "8"
      script:
        - npm install coveralls
        - npm run coverage
        - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls || true
