name: Node CI

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8.x, 10.x, 12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Project setup `npm ci`
      run: npm ci
    - name: Run `test`
      run: npm test


  coverage:
    needs: [test]
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Project setup `npm ci`
      run: npm ci

    - name: Run `coverage`
      run: npm run coverage
    - name: Export `coverage`
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./coverage/lcov.info # optional (default value)
    - name: Upload `coverage` artifact
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage/lcov-report


  # stryker:
  #   needs: [test]
  #   runs-on: ubuntu-latest
        
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: 12.x
  #   - name: Project setup `npm ci`
  #     run: npm ci

  #   - name: Run `stryker`
  #     run: npm run stryker
  #   - name: Upload `stryker` artifact
  #     uses: actions/upload-artifact@v1
  #     with:
  #       name: stryker
  #       path: reports/mutation/html
