name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1

      - name: Node 🧰
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install 📦
        run: yarn --immutable

      - name: Build 🛠
        run: yarn build

      - name: Publish 🚀 PRERELEASE
        if: 'github.event.release.prerelease'
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          yarn publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish 🚀 PRODUCTION
        if: '!github.event.release.prerelease'
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
